version: "3"

services:
  ex2-3-front:
    image: front
    environment:
      - API_URL=http://127.0.0.1/api
    ports:
      - 5000:5000
  ex2-3-backend:
    image: backend
    environment:
      - FRONT_URL=http://127.0.0.1/
      - REDIS=redis
      - DB_USERNAME=skx
      - DB_PASSWORD=secret
      - DB_HOST=psql
    ports:
      - 8000:8000
  redis:
    image: redis
    volumes:
     - ./redis.state:/data
  psql:
    image: postgres
    environment:
      - POSTGRES_USER=skx
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./psql.state:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
